import NextHead from "next/head";

export default function Head() {
  return (
    <NextHead>
      <title>Coinhall Alerts</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link
        href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;700&family=Ubuntu+Mono&display=swap"
        rel="stylesheet"
      />
    </NextHead>
  );
}
